[uwsgi]
buffer-size = 32768
enable-threads = true
http-socket = :80
lazy-apps = true
master = True
max-requests = 1
module = dd_panic.wsgi:application
pidfile = /tmp/repro.pid
processes = 1
vacuum = true
